# Go Unit Test workflow
name: 'Unit Tests'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, development ]
  pull_request:  
permissions:
    contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "gotest"
  gotest:
    name: test
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps:  # Steps represent a sequence of tasks that will be executed as part of the job
    # Installs go so job can access it
    - name: Go Install
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v3

    # Run the project's unit test
    - name: Test
      run: go test -v ./...
